---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lemacksmedia/repositories/VetWiki   # Path to the deployment directory
    - /bin/cp -R * $DEPLOYPATH                      # Copy all files to the deployment directory
    - /bin/chmod -R 755 $DEPLOYPATH                  # Set appropriate permissions
    - /bin/chown -R lemacksmedia:lemacksmedia $DEPLOYPATH    # Set ownership
